version: '3'
services:
    frontend:
        build: frontend
        container_name: frontend
        depends_on:
            - master
        environment:
            - NUM_SERVERS=$NUM_SERVERS
            - FROM_PORT=$FROM_PORT
            - TO_PORT=$TO_PORT
        ports:
            - 8000:80
    master:
        build: master
        container_name: master
        tty: true
        depends_on:
            - proxy
        environment:
            - NUM_SERVERS=$NUM_SERVERS
            - FROM_PORT=$FROM_PORT
            - TO_PORT=$TO_PORT
    proxy:
        image: shopify/toxiproxy
        container_name: proxy
        ports:
            - $FROM_PORT-$TO_PORT:$FROM_PORT-$TO_PORT
        depends_on:
            - server
    server:
        build: server
        tty: true
        environment:
            - NUM_SERVERS=$NUM_SERVERS
            - FROM_PORT=$FROM_PORT
            - PROXY_DOMAIN="proxy"